// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: scmj.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PROTOID int32

const (
	PROTOID_EMPTY PROTOID = 0
	// 登录
	PROTOID_CS_LOGIN PROTOID = 1
	PROTOID_SC_LOGIN PROTOID = 2
	// 创建牌桌
	PROTOID_CS_CREATE_TABLE PROTOID = 3
	PROTOID_SC_TABLE_INFO   PROTOID = 4
	// 加入牌桌
	PROTOID_CS_JOIN_TABLE PROTOID = 5
	PROTOID_SC_JOIN_TABLE PROTOID = 6
	// 通知手牌
	PROTOID_SC_CARD_INFO PROTOID = 7
	// 通知游戏局数开始
	PROTOID_SC_GAME_START PROTOID = 8
	// 摸牌
	PROTOID_SC_DRAW_CARD PROTOID = 9
	// 胡，杠，碰，过，出牌
	PROTOID_CS_DO_OPERATE     PROTOID = 10
	PROTOID_SC_NOTIFY_OPERATE PROTOID = 11
	// 通知客户端可以执行的操作
	PROTOID_SC_PLAYER_OPERATE PROTOID = 12
	PROTOID_CS_PLAYER_READY   PROTOID = 13
	PROTOID_SC_PLAYER_READY   PROTOID = 14
	PROTOID_SC_GAME_END       PROTOID = 15
)

// Enum value maps for PROTOID.
var (
	PROTOID_name = map[int32]string{
		0:  "EMPTY",
		1:  "CS_LOGIN",
		2:  "SC_LOGIN",
		3:  "CS_CREATE_TABLE",
		4:  "SC_TABLE_INFO",
		5:  "CS_JOIN_TABLE",
		6:  "SC_JOIN_TABLE",
		7:  "SC_CARD_INFO",
		8:  "SC_GAME_START",
		9:  "SC_DRAW_CARD",
		10: "CS_DO_OPERATE",
		11: "SC_NOTIFY_OPERATE",
		12: "SC_PLAYER_OPERATE",
		13: "CS_PLAYER_READY",
		14: "SC_PLAYER_READY",
		15: "SC_GAME_END",
	}
	PROTOID_value = map[string]int32{
		"EMPTY":             0,
		"CS_LOGIN":          1,
		"SC_LOGIN":          2,
		"CS_CREATE_TABLE":   3,
		"SC_TABLE_INFO":     4,
		"CS_JOIN_TABLE":     5,
		"SC_JOIN_TABLE":     6,
		"SC_CARD_INFO":      7,
		"SC_GAME_START":     8,
		"SC_DRAW_CARD":      9,
		"CS_DO_OPERATE":     10,
		"SC_NOTIFY_OPERATE": 11,
		"SC_PLAYER_OPERATE": 12,
		"CS_PLAYER_READY":   13,
		"SC_PLAYER_READY":   14,
		"SC_GAME_END":       15,
	}
)

func (x PROTOID) Enum() *PROTOID {
	p := new(PROTOID)
	*p = x
	return p
}

func (x PROTOID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PROTOID) Descriptor() protoreflect.EnumDescriptor {
	return file_scmj_proto_enumTypes[0].Descriptor()
}

func (PROTOID) Type() protoreflect.EnumType {
	return &file_scmj_proto_enumTypes[0]
}

func (x PROTOID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PROTOID.Descriptor instead.
func (PROTOID) EnumDescriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{0}
}

type PLAY_MODE int32

const (
	PLAY_MODE_XLCH PLAY_MODE = 0 // 血流成河
	PLAY_MODE_XZDD PLAY_MODE = 1 // 血战到底
)

// Enum value maps for PLAY_MODE.
var (
	PLAY_MODE_name = map[int32]string{
		0: "XLCH",
		1: "XZDD",
	}
	PLAY_MODE_value = map[string]int32{
		"XLCH": 0,
		"XZDD": 1,
	}
)

func (x PLAY_MODE) Enum() *PLAY_MODE {
	p := new(PLAY_MODE)
	*p = x
	return p
}

func (x PLAY_MODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PLAY_MODE) Descriptor() protoreflect.EnumDescriptor {
	return file_scmj_proto_enumTypes[1].Descriptor()
}

func (PLAY_MODE) Type() protoreflect.EnumType {
	return &file_scmj_proto_enumTypes[1]
}

func (x PLAY_MODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PLAY_MODE.Descriptor instead.
func (PLAY_MODE) EnumDescriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{1}
}

type CsLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CsLogin) Reset() {
	*x = CsLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsLogin) ProtoMessage() {}

func (x *CsLogin) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsLogin.ProtoReflect.Descriptor instead.
func (*CsLogin) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{0}
}

func (x *CsLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CsLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ScLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Pid      uint64 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sex      int32  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`                           // 性别
	RoomCard int64  `protobuf:"varint,5,opt,name=room_card,json=roomCard,proto3" json:"room_card,omitempty"` // 房卡数量
}

func (x *ScLogin) Reset() {
	*x = ScLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScLogin) ProtoMessage() {}

func (x *ScLogin) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScLogin.ProtoReflect.Descriptor instead.
func (*ScLogin) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{1}
}

func (x *ScLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ScLogin) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ScLogin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScLogin) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *ScLogin) GetRoomCard() int64 {
	if x != nil {
		return x.RoomCard
	}
	return 0
}

type ScmjData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayMode      uint32 `protobuf:"varint,1,opt,name=play_mode,json=playMode,proto3" json:"play_mode,omitempty"`
	PlayTurn      uint32 `protobuf:"varint,2,opt,name=play_turn,json=playTurn,proto3" json:"play_turn,omitempty"`                  // 局数
	MaxPoint      uint32 `protobuf:"varint,3,opt,name=max_point,json=maxPoint,proto3" json:"max_point,omitempty"`                  // 最大番数
	SelfWinType   uint32 `protobuf:"varint,4,opt,name=self_win_type,json=selfWinType,proto3" json:"self_win_type,omitempty"`       // 自摸加底或者加番
	ExposeWinType uint32 `protobuf:"varint,5,opt,name=expose_win_type,json=exposeWinType,proto3" json:"expose_win_type,omitempty"` // 点杠花点炮或者点杠花自摸
	HszSwitch     uint32 `protobuf:"varint,6,opt,name=hsz_switch,json=hszSwitch,proto3" json:"hsz_switch,omitempty"`               // 是否换三张
	JdSwitch      uint32 `protobuf:"varint,7,opt,name=jd_switch,json=jdSwitch,proto3" json:"jd_switch,omitempty"`                  // 是否算将对
	MqzzSwitch    uint32 `protobuf:"varint,8,opt,name=mqzz_switch,json=mqzzSwitch,proto3" json:"mqzz_switch,omitempty"`            // 是否算门清中张
	TdhSwitch     uint32 `protobuf:"varint,9,opt,name=tdh_switch,json=tdhSwitch,proto3" json:"tdh_switch,omitempty"`               // 是否有天地胡
	MaxPlayer     uint32 `protobuf:"varint,10,opt,name=max_player,json=maxPlayer,proto3" json:"max_player,omitempty"`              // 最大游戏人数
}

func (x *ScmjData) Reset() {
	*x = ScmjData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScmjData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScmjData) ProtoMessage() {}

func (x *ScmjData) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScmjData.ProtoReflect.Descriptor instead.
func (*ScmjData) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{2}
}

func (x *ScmjData) GetPlayMode() uint32 {
	if x != nil {
		return x.PlayMode
	}
	return 0
}

func (x *ScmjData) GetPlayTurn() uint32 {
	if x != nil {
		return x.PlayTurn
	}
	return 0
}

func (x *ScmjData) GetMaxPoint() uint32 {
	if x != nil {
		return x.MaxPoint
	}
	return 0
}

func (x *ScmjData) GetSelfWinType() uint32 {
	if x != nil {
		return x.SelfWinType
	}
	return 0
}

func (x *ScmjData) GetExposeWinType() uint32 {
	if x != nil {
		return x.ExposeWinType
	}
	return 0
}

func (x *ScmjData) GetHszSwitch() uint32 {
	if x != nil {
		return x.HszSwitch
	}
	return 0
}

func (x *ScmjData) GetJdSwitch() uint32 {
	if x != nil {
		return x.JdSwitch
	}
	return 0
}

func (x *ScmjData) GetMqzzSwitch() uint32 {
	if x != nil {
		return x.MqzzSwitch
	}
	return 0
}

func (x *ScmjData) GetTdhSwitch() uint32 {
	if x != nil {
		return x.TdhSwitch
	}
	return 0
}

func (x *ScmjData) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

type CsCreateScmjTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ScmjData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CsCreateScmjTable) Reset() {
	*x = CsCreateScmjTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsCreateScmjTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCreateScmjTable) ProtoMessage() {}

func (x *CsCreateScmjTable) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCreateScmjTable.ProtoReflect.Descriptor instead.
func (*CsCreateScmjTable) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{3}
}

func (x *CsCreateScmjTable) GetData() *ScmjData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TablePlayerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid         uint64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Photo       uint32 `protobuf:"varint,2,opt,name=photo,proto3" json:"photo,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                   // 名字
	Identity    uint32 `protobuf:"varint,4,opt,name=identity,proto3" json:"identity,omitempty"`                          // 身份
	OnlineState uint32 `protobuf:"varint,5,opt,name=online_state,json=onlineState,proto3" json:"online_state,omitempty"` // 在线状态
}

func (x *TablePlayerData) Reset() {
	*x = TablePlayerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TablePlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TablePlayerData) ProtoMessage() {}

func (x *TablePlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TablePlayerData.ProtoReflect.Descriptor instead.
func (*TablePlayerData) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{4}
}

func (x *TablePlayerData) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TablePlayerData) GetPhoto() uint32 {
	if x != nil {
		return x.Photo
	}
	return 0
}

func (x *TablePlayerData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TablePlayerData) GetIdentity() uint32 {
	if x != nil {
		return x.Identity
	}
	return 0
}

func (x *TablePlayerData) GetOnlineState() uint32 {
	if x != nil {
		return x.OnlineState
	}
	return 0
}

type ScScmjTableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId   uint32             `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Data      *ScmjData          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	StartTime int64              `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Players   []*TablePlayerData `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *ScScmjTableInfo) Reset() {
	*x = ScScmjTableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScScmjTableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScScmjTableInfo) ProtoMessage() {}

func (x *ScScmjTableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScScmjTableInfo.ProtoReflect.Descriptor instead.
func (*ScScmjTableInfo) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{5}
}

func (x *ScScmjTableInfo) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *ScScmjTableInfo) GetData() *ScmjData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScScmjTableInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ScScmjTableInfo) GetPlayers() []*TablePlayerData {
	if x != nil {
		return x.Players
	}
	return nil
}

type CsJoinTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId  uint32 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Identity uint32 `protobuf:"varint,2,opt,name=identity,proto3" json:"identity,omitempty"` // 身份
}

func (x *CsJoinTable) Reset() {
	*x = CsJoinTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsJoinTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsJoinTable) ProtoMessage() {}

func (x *CsJoinTable) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsJoinTable.ProtoReflect.Descriptor instead.
func (*CsJoinTable) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{6}
}

func (x *CsJoinTable) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *CsJoinTable) GetIdentity() uint32 {
	if x != nil {
		return x.Identity
	}
	return 0
}

type ScJoinTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatIndex int32            `protobuf:"varint,1,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"` // 位置索引
	Player    *TablePlayerData `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *ScJoinTable) Reset() {
	*x = ScJoinTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScJoinTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScJoinTable) ProtoMessage() {}

func (x *ScJoinTable) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScJoinTable.ProtoReflect.Descriptor instead.
func (*ScJoinTable) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{7}
}

func (x *ScJoinTable) GetSeatIndex() int32 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *ScJoinTable) GetPlayer() *TablePlayerData {
	if x != nil {
		return x.Player
	}
	return nil
}

type KongInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card     int32 `protobuf:"varint,1,opt,name=card,proto3" json:"card,omitempty"`
	KongType int32 `protobuf:"varint,2,opt,name=kong_type,json=kongType,proto3" json:"kong_type,omitempty"`
}

func (x *KongInfo) Reset() {
	*x = KongInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KongInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KongInfo) ProtoMessage() {}

func (x *KongInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KongInfo.ProtoReflect.Descriptor instead.
func (*KongInfo) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{8}
}

func (x *KongInfo) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

func (x *KongInfo) GetKongType() int32 {
	if x != nil {
		return x.KongType
	}
	return 0
}

type HandCardData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Holders []int32     `protobuf:"varint,1,rep,packed,name=holders,proto3" json:"holders,omitempty"`
	Pong    []int32     `protobuf:"varint,2,rep,packed,name=pong,proto3" json:"pong,omitempty"`
	Kong    []*KongInfo `protobuf:"bytes,3,rep,name=kong,proto3" json:"kong,omitempty"`
	Draw    int32       `protobuf:"varint,4,opt,name=draw,proto3" json:"draw,omitempty"` // 摸的牌
}

func (x *HandCardData) Reset() {
	*x = HandCardData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandCardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandCardData) ProtoMessage() {}

func (x *HandCardData) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandCardData.ProtoReflect.Descriptor instead.
func (*HandCardData) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{9}
}

func (x *HandCardData) GetHolders() []int32 {
	if x != nil {
		return x.Holders
	}
	return nil
}

func (x *HandCardData) GetPong() []int32 {
	if x != nil {
		return x.Pong
	}
	return nil
}

func (x *HandCardData) GetKong() []*KongInfo {
	if x != nil {
		return x.Kong
	}
	return nil
}

func (x *HandCardData) GetDraw() int32 {
	if x != nil {
		return x.Draw
	}
	return 0
}

type PlayerCardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandCard *HandCardData `protobuf:"bytes,1,opt,name=hand_card,json=handCard,proto3" json:"hand_card,omitempty"`
	OutCard  []int32       `protobuf:"varint,2,rep,packed,name=out_card,json=outCard,proto3" json:"out_card,omitempty"`
}

func (x *PlayerCardInfo) Reset() {
	*x = PlayerCardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCardInfo) ProtoMessage() {}

func (x *PlayerCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCardInfo.ProtoReflect.Descriptor instead.
func (*PlayerCardInfo) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerCardInfo) GetHandCard() *HandCardData {
	if x != nil {
		return x.HandCard
	}
	return nil
}

func (x *PlayerCardInfo) GetOutCard() []int32 {
	if x != nil {
		return x.OutCard
	}
	return nil
}

type TableCardData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 总的牌
	Left  int32 `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`   // 剩余的牌
}

func (x *TableCardData) Reset() {
	*x = TableCardData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableCardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCardData) ProtoMessage() {}

func (x *TableCardData) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCardData.ProtoReflect.Descriptor instead.
func (*TableCardData) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{11}
}

func (x *TableCardData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TableCardData) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

type ScCardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardInfo  []*PlayerCardInfo `protobuf:"bytes,1,rep,name=card_info,json=cardInfo,proto3" json:"card_info,omitempty"`
	TableCard *TableCardData    `protobuf:"bytes,2,opt,name=table_card,json=tableCard,proto3" json:"table_card,omitempty"`
}

func (x *ScCardInfo) Reset() {
	*x = ScCardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScCardInfo) ProtoMessage() {}

func (x *ScCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScCardInfo.ProtoReflect.Descriptor instead.
func (*ScCardInfo) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{12}
}

func (x *ScCardInfo) GetCardInfo() []*PlayerCardInfo {
	if x != nil {
		return x.CardInfo
	}
	return nil
}

func (x *ScCardInfo) GetTableCard() *TableCardData {
	if x != nil {
		return x.TableCard
	}
	return nil
}

type ScGameStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiePoint int32 `protobuf:"varint,1,opt,name=die_point,json=diePoint,proto3" json:"die_point,omitempty"` // 筛子点数
	Games    int32 `protobuf:"varint,2,opt,name=games,proto3" json:"games,omitempty"`                       // 游戏局数
}

func (x *ScGameStart) Reset() {
	*x = ScGameStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScGameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScGameStart) ProtoMessage() {}

func (x *ScGameStart) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScGameStart.ProtoReflect.Descriptor instead.
func (*ScGameStart) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{13}
}

func (x *ScGameStart) GetDiePoint() int32 {
	if x != nil {
		return x.DiePoint
	}
	return 0
}

func (x *ScGameStart) GetGames() int32 {
	if x != nil {
		return x.Games
	}
	return 0
}

type ScWinInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinCard   int32   `protobuf:"varint,1,opt,name=win_card,json=winCard,proto3" json:"win_card,omitempty"`
	CardModel []int32 `protobuf:"varint,2,rep,packed,name=card_model,json=cardModel,proto3" json:"card_model,omitempty"`
	WinMode   int32   `protobuf:"varint,3,opt,name=win_mode,json=winMode,proto3" json:"win_mode,omitempty"` // 胡牌模式（自摸，天胡，杠上花等）
	Point     int32   `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`                    // 番数
	WinTime   int64   `protobuf:"varint,5,opt,name=win_time,json=winTime,proto3" json:"win_time,omitempty"` // 时间
}

func (x *ScWinInfo) Reset() {
	*x = ScWinInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScWinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScWinInfo) ProtoMessage() {}

func (x *ScWinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScWinInfo.ProtoReflect.Descriptor instead.
func (*ScWinInfo) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{14}
}

func (x *ScWinInfo) GetWinCard() int32 {
	if x != nil {
		return x.WinCard
	}
	return 0
}

func (x *ScWinInfo) GetCardModel() []int32 {
	if x != nil {
		return x.CardModel
	}
	return nil
}

func (x *ScWinInfo) GetWinMode() int32 {
	if x != nil {
		return x.WinMode
	}
	return 0
}

func (x *ScWinInfo) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *ScWinInfo) GetWinTime() int64 {
	if x != nil {
		return x.WinTime
	}
	return 0
}

type ScLoseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoseCard int32 `protobuf:"varint,1,opt,name=lose_card,json=loseCard,proto3" json:"lose_card,omitempty"`
	LoseMode int32 `protobuf:"varint,2,opt,name=lose_mode,json=loseMode,proto3" json:"lose_mode,omitempty"` // 胡牌模式（自摸，天胡，杠上花等）
	LoseTime int64 `protobuf:"varint,3,opt,name=lose_time,json=loseTime,proto3" json:"lose_time,omitempty"` // 时间
}

func (x *ScLoseInfo) Reset() {
	*x = ScLoseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScLoseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScLoseInfo) ProtoMessage() {}

func (x *ScLoseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScLoseInfo.ProtoReflect.Descriptor instead.
func (*ScLoseInfo) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{15}
}

func (x *ScLoseInfo) GetLoseCard() int32 {
	if x != nil {
		return x.LoseCard
	}
	return 0
}

func (x *ScLoseInfo) GetLoseMode() int32 {
	if x != nil {
		return x.LoseMode
	}
	return 0
}

func (x *ScLoseInfo) GetLoseTime() int64 {
	if x != nil {
		return x.LoseTime
	}
	return 0
}

type ScSummaryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardInfo *PlayerCardInfo `protobuf:"bytes,1,opt,name=card_info,json=cardInfo,proto3" json:"card_info,omitempty"`
	WinInfo  []*ScWinInfo    `protobuf:"bytes,2,rep,name=win_info,json=winInfo,proto3" json:"win_info,omitempty"` // 牌型
	LoseInfo []*ScLoseInfo   `protobuf:"bytes,3,rep,name=lose_info,json=loseInfo,proto3" json:"lose_info,omitempty"`
	Score    int32           `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"` // 得分
}

func (x *ScSummaryInfo) Reset() {
	*x = ScSummaryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScSummaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScSummaryInfo) ProtoMessage() {}

func (x *ScSummaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScSummaryInfo.ProtoReflect.Descriptor instead.
func (*ScSummaryInfo) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{16}
}

func (x *ScSummaryInfo) GetCardInfo() *PlayerCardInfo {
	if x != nil {
		return x.CardInfo
	}
	return nil
}

func (x *ScSummaryInfo) GetWinInfo() []*ScWinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *ScSummaryInfo) GetLoseInfo() []*ScLoseInfo {
	if x != nil {
		return x.LoseInfo
	}
	return nil
}

func (x *ScSummaryInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ScGameEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games   int32            `protobuf:"varint,1,opt,name=games,proto3" json:"games,omitempty"` // 局数
	Summary []*ScSummaryInfo `protobuf:"bytes,2,rep,name=summary,proto3" json:"summary,omitempty"`
}

func (x *ScGameEnd) Reset() {
	*x = ScGameEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScGameEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScGameEnd) ProtoMessage() {}

func (x *ScGameEnd) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScGameEnd.ProtoReflect.Descriptor instead.
func (*ScGameEnd) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{17}
}

func (x *ScGameEnd) GetGames() int32 {
	if x != nil {
		return x.Games
	}
	return 0
}

func (x *ScGameEnd) GetSummary() []*ScSummaryInfo {
	if x != nil {
		return x.Summary
	}
	return nil
}

type ScDrawCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid  uint64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Card int32  `protobuf:"varint,2,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *ScDrawCard) Reset() {
	*x = ScDrawCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScDrawCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScDrawCard) ProtoMessage() {}

func (x *ScDrawCard) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScDrawCard.ProtoReflect.Descriptor instead.
func (*ScDrawCard) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{18}
}

func (x *ScDrawCard) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ScDrawCard) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

type OperateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card int32 `protobuf:"varint,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *OperateData) Reset() {
	*x = OperateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateData) ProtoMessage() {}

func (x *OperateData) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateData.ProtoReflect.Descriptor instead.
func (*OperateData) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{19}
}

func (x *OperateData) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

type CsDoOperate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpType int32        `protobuf:"varint,2,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	Data   *OperateData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CsDoOperate) Reset() {
	*x = CsDoOperate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsDoOperate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsDoOperate) ProtoMessage() {}

func (x *CsDoOperate) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsDoOperate.ProtoReflect.Descriptor instead.
func (*CsDoOperate) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{20}
}

func (x *CsDoOperate) GetOpType() int32 {
	if x != nil {
		return x.OpType
	}
	return 0
}

func (x *CsDoOperate) GetData() *OperateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ScNotifyOperate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid    uint64       `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	OpType int32        `protobuf:"varint,2,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	Data   *OperateData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ScNotifyOperate) Reset() {
	*x = ScNotifyOperate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScNotifyOperate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScNotifyOperate) ProtoMessage() {}

func (x *ScNotifyOperate) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScNotifyOperate.ProtoReflect.Descriptor instead.
func (*ScNotifyOperate) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{21}
}

func (x *ScNotifyOperate) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ScNotifyOperate) GetOpType() int32 {
	if x != nil {
		return x.OpType
	}
	return 0
}

func (x *ScNotifyOperate) GetData() *OperateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ScPlayerOperate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpType []int32 `protobuf:"varint,1,rep,packed,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
}

func (x *ScPlayerOperate) Reset() {
	*x = ScPlayerOperate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScPlayerOperate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScPlayerOperate) ProtoMessage() {}

func (x *ScPlayerOperate) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScPlayerOperate.ProtoReflect.Descriptor instead.
func (*ScPlayerOperate) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{22}
}

func (x *ScPlayerOperate) GetOpType() []int32 {
	if x != nil {
		return x.OpType
	}
	return nil
}

type CsPlayerReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
}

func (x *CsPlayerReady) Reset() {
	*x = CsPlayerReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsPlayerReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsPlayerReady) ProtoMessage() {}

func (x *CsPlayerReady) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsPlayerReady.ProtoReflect.Descriptor instead.
func (*CsPlayerReady) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{23}
}

func (x *CsPlayerReady) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ScPlayerReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid   uint64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ready bool   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
}

func (x *ScPlayerReady) Reset() {
	*x = ScPlayerReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scmj_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScPlayerReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScPlayerReady) ProtoMessage() {}

func (x *ScPlayerReady) ProtoReflect() protoreflect.Message {
	mi := &file_scmj_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScPlayerReady.ProtoReflect.Descriptor instead.
func (*ScPlayerReady) Descriptor() ([]byte, []int) {
	return file_scmj_proto_rawDescGZIP(), []int{24}
}

func (x *ScPlayerReady) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ScPlayerReady) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

var File_scmj_proto protoreflect.FileDescriptor

var file_scmj_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x63, 0x6d, 0x6a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x40, 0x0a, 0x08, 0x63, 0x73, 0x5f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x79, 0x0a, 0x08, 0x73, 0x63, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63,
	0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x43,
	0x61, 0x72, 0x64, 0x22, 0xc9, 0x02, 0x0a, 0x09, 0x73, 0x63, 0x6d, 0x6a, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x75, 0x72, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x61, 0x78, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x6d, 0x61, 0x78, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x65, 0x6c, 0x66,
	0x5f, 0x77, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x73, 0x65, 0x6c, 0x66, 0x57, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f,
	0x65, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x57, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x73, 0x7a, 0x5f, 0x73, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68, 0x73, 0x7a, 0x53, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x64, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6a, 0x64, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x71, 0x7a, 0x7a, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x71, 0x7a, 0x7a, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x64, 0x68, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x64, 0x68, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22,
	0x3f, 0x0a, 0x14, 0x63, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x63, 0x6d,
	0x6a, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x73, 0x63, 0x6d, 0x6a, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x8e, 0x01, 0x0a, 0x11, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x22, 0xae, 0x01, 0x0a, 0x12, 0x73, 0x63, 0x5f, 0x73, 0x63, 0x6d, 0x6a, 0x5f, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x73, 0x63, 0x6d,
	0x6a, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x22, 0x46, 0x0a, 0x0d, 0x63, 0x73, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x63, 0x0a, 0x0d, 0x73, 0x63,
	0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x73, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x33, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22,
	0x3c, 0x0a, 0x09, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6b, 0x6f, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22, 0x7b, 0x0a,
	0x0e, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x07, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x27, 0x0a,
	0x04, 0x6b, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x6b, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x72, 0x61, 0x77, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x72, 0x61, 0x77, 0x22, 0x64, 0x0a, 0x10, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x35,
	0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x68, 0x61, 0x6e,
	0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x68, 0x61, 0x6e,
	0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x22, 0x3b, 0x0a, 0x0f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x22, 0x81, 0x01,
	0x0a, 0x0c, 0x73, 0x63, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x37,
	0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63,
	0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x72,
	0x64, 0x22, 0x42, 0x0a, 0x0d, 0x73, 0x63, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x65, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x0b, 0x73, 0x63, 0x5f, 0x77, 0x69, 0x6e,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x63, 0x61, 0x72, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x19, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x65, 0x0a, 0x0c, 0x73,
	0x63, 0x5f, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x6c,
	0x6f, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6c, 0x6f, 0x73, 0x65, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x73, 0x65,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x6f, 0x73,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x0f, 0x73, 0x63, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x30, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x73, 0x63, 0x5f,
	0x77, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x33, 0x0a, 0x09, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x73, 0x63, 0x5f, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6c, 0x6f,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x58, 0x0a, 0x0b,
	0x73, 0x63, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x33, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x73, 0x63,
	0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x34, 0x0a, 0x0c, 0x73, 0x63, 0x5f, 0x64, 0x72, 0x61,
	0x77, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x22, 0x0a, 0x0c,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x22, 0x54, 0x0a, 0x0d, 0x63, 0x73, 0x5f, 0x64, 0x6f, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6a, 0x0a, 0x11, 0x73, 0x63, 0x5f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x2c, 0x0a, 0x11, 0x73, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x27, 0x0a, 0x0f, 0x63, 0x73, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x22, 0x39, 0x0a, 0x0f, 0x73, 0x63, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x2a, 0xb1, 0x02, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x49, 0x44,
	0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43,
	0x53, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x43, 0x5f,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x53, 0x5f, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d,
	0x53, 0x43, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x04, 0x12,
	0x11, 0x0a, 0x0d, 0x43, 0x53, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45,
	0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x43, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x5f, 0x54, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x43, 0x5f, 0x43, 0x41, 0x52, 0x44,
	0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x07, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x43, 0x5f, 0x47, 0x41,
	0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x08, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x43,
	0x5f, 0x44, 0x52, 0x41, 0x57, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10, 0x09, 0x12, 0x11, 0x0a, 0x0d,
	0x43, 0x53, 0x5f, 0x44, 0x4f, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x45, 0x10, 0x0a, 0x12,
	0x15, 0x0a, 0x11, 0x53, 0x43, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x4f, 0x50, 0x45,
	0x52, 0x41, 0x54, 0x45, 0x10, 0x0b, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x43, 0x5f, 0x50, 0x4c, 0x41,
	0x59, 0x45, 0x52, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x45, 0x10, 0x0c, 0x12, 0x13, 0x0a,
	0x0f, 0x43, 0x53, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59,
	0x10, 0x0d, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x43, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f,
	0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x0e, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x43, 0x5f, 0x47, 0x41,
	0x4d, 0x45, 0x5f, 0x45, 0x4e, 0x44, 0x10, 0x0f, 0x2a, 0x1f, 0x0a, 0x09, 0x50, 0x4c, 0x41, 0x59,
	0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x12, 0x08, 0x0a, 0x04, 0x58, 0x4c, 0x43, 0x48, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x58, 0x5a, 0x44, 0x44, 0x10, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_scmj_proto_rawDescOnce sync.Once
	file_scmj_proto_rawDescData = file_scmj_proto_rawDesc
)

func file_scmj_proto_rawDescGZIP() []byte {
	file_scmj_proto_rawDescOnce.Do(func() {
		file_scmj_proto_rawDescData = protoimpl.X.CompressGZIP(file_scmj_proto_rawDescData)
	})
	return file_scmj_proto_rawDescData
}

var file_scmj_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scmj_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_scmj_proto_goTypes = []interface{}{
	(PROTOID)(0),              // 0: protocol.PROTOID
	(PLAY_MODE)(0),            // 1: protocol.PLAY_MODE
	(*CsLogin)(nil),           // 2: protocol.cs_login
	(*ScLogin)(nil),           // 3: protocol.sc_login
	(*ScmjData)(nil),          // 4: protocol.scmj_data
	(*CsCreateScmjTable)(nil), // 5: protocol.cs_create_scmj_table
	(*TablePlayerData)(nil),   // 6: protocol.table_player_data
	(*ScScmjTableInfo)(nil),   // 7: protocol.sc_scmj_table_info
	(*CsJoinTable)(nil),       // 8: protocol.cs_join_table
	(*ScJoinTable)(nil),       // 9: protocol.sc_join_table
	(*KongInfo)(nil),          // 10: protocol.kong_info
	(*HandCardData)(nil),      // 11: protocol.hand_card_data
	(*PlayerCardInfo)(nil),    // 12: protocol.player_card_info
	(*TableCardData)(nil),     // 13: protocol.table_card_data
	(*ScCardInfo)(nil),        // 14: protocol.sc_card_info
	(*ScGameStart)(nil),       // 15: protocol.sc_game_start
	(*ScWinInfo)(nil),         // 16: protocol.sc_win_info
	(*ScLoseInfo)(nil),        // 17: protocol.sc_lose_info
	(*ScSummaryInfo)(nil),     // 18: protocol.sc_summary_info
	(*ScGameEnd)(nil),         // 19: protocol.sc_game_end
	(*ScDrawCard)(nil),        // 20: protocol.sc_draw_card
	(*OperateData)(nil),       // 21: protocol.operate_data
	(*CsDoOperate)(nil),       // 22: protocol.cs_do_operate
	(*ScNotifyOperate)(nil),   // 23: protocol.sc_notify_operate
	(*ScPlayerOperate)(nil),   // 24: protocol.sc_player_operate
	(*CsPlayerReady)(nil),     // 25: protocol.cs_player_ready
	(*ScPlayerReady)(nil),     // 26: protocol.sc_player_ready
}
var file_scmj_proto_depIdxs = []int32{
	4,  // 0: protocol.cs_create_scmj_table.data:type_name -> protocol.scmj_data
	4,  // 1: protocol.sc_scmj_table_info.data:type_name -> protocol.scmj_data
	6,  // 2: protocol.sc_scmj_table_info.players:type_name -> protocol.table_player_data
	6,  // 3: protocol.sc_join_table.player:type_name -> protocol.table_player_data
	10, // 4: protocol.hand_card_data.kong:type_name -> protocol.kong_info
	11, // 5: protocol.player_card_info.hand_card:type_name -> protocol.hand_card_data
	12, // 6: protocol.sc_card_info.card_info:type_name -> protocol.player_card_info
	13, // 7: protocol.sc_card_info.table_card:type_name -> protocol.table_card_data
	12, // 8: protocol.sc_summary_info.card_info:type_name -> protocol.player_card_info
	16, // 9: protocol.sc_summary_info.win_info:type_name -> protocol.sc_win_info
	17, // 10: protocol.sc_summary_info.lose_info:type_name -> protocol.sc_lose_info
	18, // 11: protocol.sc_game_end.summary:type_name -> protocol.sc_summary_info
	21, // 12: protocol.cs_do_operate.data:type_name -> protocol.operate_data
	21, // 13: protocol.sc_notify_operate.data:type_name -> protocol.operate_data
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_scmj_proto_init() }
func file_scmj_proto_init() {
	if File_scmj_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scmj_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScmjData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsCreateScmjTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TablePlayerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScScmjTableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsJoinTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScJoinTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KongInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandCardData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerCardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableCardData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScCardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScGameStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScWinInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScLoseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScSummaryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScGameEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScDrawCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsDoOperate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScNotifyOperate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScPlayerOperate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsPlayerReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scmj_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScPlayerReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scmj_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scmj_proto_goTypes,
		DependencyIndexes: file_scmj_proto_depIdxs,
		EnumInfos:         file_scmj_proto_enumTypes,
		MessageInfos:      file_scmj_proto_msgTypes,
	}.Build()
	File_scmj_proto = out.File
	file_scmj_proto_rawDesc = nil
	file_scmj_proto_goTypes = nil
	file_scmj_proto_depIdxs = nil
}
